name: build
on: [push]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    name: build
    needs: ci

    permissions:
      packages: write

    uses: evanpurkhiser/workflows/.github/workflows/docker.yml@main
    with:
      publish: ${{ github.ref == 'refs/heads/main' }}
